USE ROLE E2E_SNOW_MLOPS_ROLE;
USE WAREHOUSE E2E_SNOW_MLOPS_WH;
USE DATABASE E2E_SNOW_MLOPS_DB;
USE SCHEMA MLOPS_SCHEMA;

CREATE OR REPLACE TABLE PAPERS (
    PAPER_ID STRING NOT NULL,
    ARXIV_ID STRING,
    TITLE STRING,
    ABSTRACT STRING,
    PUBLICATION_YEAR NUMBER,
    PRIMARY_TOPIC STRING,
    CITED_BY_COUNT NUMBER,
    CITATIONS_PER_YEAR FLOAT,
    IS_FOCAL BOOLEAN,
    ARXIV_URL STRING,
    TEXT_FOR_SEARCH STRING,
    CONSTRAINT PK_PAPERS PRIMARY KEY (PAPER_ID)
);

CREATE OR REPLACE TABLE CITATION_EDGES (
    CITING_PAPER_ID STRING NOT NULL,
    CITED_PAPER_ID STRING NOT NULL
);

CREATE OR REPLACE TABLE PROMPT_USAGE (
    USER_KEY STRING NOT NULL,
    USED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    USAGE_DATE DATE DEFAULT CURRENT_DATE(),
    ROUTE STRING,
    QUESTION_HASH STRING,
    SUCCEEDED BOOLEAN
);

CREATE OR REPLACE TABLE QUERY_LOG (
    QUERY_ID STRING DEFAULT UUID_STRING(),
    USER_KEY STRING,
    QUESTION STRING,
    ROUTE STRING,
    GENERATED_SQL STRING,
    ANSWER STRING,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
