USE ROLE E2E_SNOW_MLOPS_ROLE;
USE WAREHOUSE E2E_SNOW_MLOPS_WH;
USE DATABASE E2E_SNOW_MLOPS_DB;
USE SCHEMA MLOPS_SCHEMA;

CREATE OR REPLACE VIEW FOCAL_PAPERS AS
SELECT * FROM PAPERS WHERE IS_FOCAL = TRUE;

CREATE OR REPLACE VIEW CITATION_RELATIONSHIPS AS
SELECT
    e.CITING_PAPER_ID,
    citing.TITLE AS CITING_TITLE,
    citing.PUBLICATION_YEAR AS CITING_YEAR,
    citing.PRIMARY_TOPIC AS CITING_TOPIC,
    citing.CITED_BY_COUNT AS CITING_CITATION_COUNT,
    e.CITED_PAPER_ID,
    cited.TITLE AS CITED_TITLE,
    cited.PUBLICATION_YEAR AS CITED_YEAR,
    cited.PRIMARY_TOPIC AS CITED_TOPIC,
    cited.CITED_BY_COUNT AS CITED_CITATION_COUNT
FROM CITATION_EDGES e
JOIN PAPERS citing ON e.CITING_PAPER_ID = citing.PAPER_ID
JOIN PAPERS cited ON e.CITED_PAPER_ID = cited.PAPER_ID;

ALTER TABLE PAPERS SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE CORTEX SEARCH SERVICE PAPER_SEARCH
ON TEXT_FOR_SEARCH
ATTRIBUTES PAPER_ID, PUBLICATION_YEAR, PRIMARY_TOPIC, IS_FOCAL
WAREHOUSE = E2E_SNOW_MLOPS_WH
TARGET_LAG = '1 day'
AS
SELECT
    PAPER_ID, TITLE, ABSTRACT, TEXT_FOR_SEARCH,
    PUBLICATION_YEAR, PRIMARY_TOPIC, CITED_BY_COUNT,
    CITATIONS_PER_YEAR, IS_FOCAL, ARXIV_URL
FROM PAPERS
WHERE ABSTRACT IS NOT NULL;
